{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.codexbat",
    "module": "vesper",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vesper-1.0.11.jar",
          "url": "vesper-1.0.11.jar",
          "size": 162292,
          "sha512": "21c948710984f5f9aa45713f2ec26eab806ec2836b4cd198a69aa91e04f7c921688f6ae400cb5d449348f88c0df8aceca99d047459b7ec9ff007f781c0975c26",
          "sha256": "6b60eb39cdd75e902821118caf14c251d9059fbf5e24e29da8e1ffb379f5b7b2",
          "sha1": "325a9535dd1d5cc7d8defa9c2b70dea193f4b795",
          "md5": "2fd1fe70a1de78b24238ee9c8f049390"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "vesper-1.0.11.jar",
          "url": "vesper-1.0.11.jar",
          "size": 162292,
          "sha512": "21c948710984f5f9aa45713f2ec26eab806ec2836b4cd198a69aa91e04f7c921688f6ae400cb5d449348f88c0df8aceca99d047459b7ec9ff007f781c0975c26",
          "sha256": "6b60eb39cdd75e902821118caf14c251d9059fbf5e24e29da8e1ffb379f5b7b2",
          "sha1": "325a9535dd1d5cc7d8defa9c2b70dea193f4b795",
          "md5": "2fd1fe70a1de78b24238ee9c8f049390"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vesper-1.0.11-sources.jar",
          "url": "vesper-1.0.11-sources.jar",
          "size": 101835,
          "sha512": "f5e6cd0f1df04aadaddd62c8e4702a0bf72b70d2d71ec4d9ac8ec325449a175143646e337719e498a1f8b34adf4b428158a14e73c05d0c9d98f586f5e4f7a3b3",
          "sha256": "db68ec1d9c264d6e5de0346eff11e24c9b87c4d29fd7ec8d9918fae5162d05be",
          "sha1": "84f543e5ee76b7239ed2b875016608948aed5290",
          "md5": "702b6dad5bdd9da49b79b579fc41ac8f"
        }
      ]
    }
  ]
}
