{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.codexbat",
    "module": "vesper",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vesper-1.0.11.jar",
          "url": "vesper-1.0.11.jar",
          "size": 162292,
          "sha512": "14274b4aabc2542aaf62e124f16c1015a00877e89c7615d02000a6d3697075dde21fd588a94872585407f03ab6d2c0f09bb0b40e2183b6798f3719123b8e9651",
          "sha256": "e0b6bf3a8d8e1918f7d8b09b60545178290bd0f5e15641180b3c2d50dca060bd",
          "sha1": "4a7fce67686e713c5581647cf85219fa28fb6687",
          "md5": "aab12ba16642a5a17bae48b7e6d3b57e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "vesper-1.0.11.jar",
          "url": "vesper-1.0.11.jar",
          "size": 162292,
          "sha512": "14274b4aabc2542aaf62e124f16c1015a00877e89c7615d02000a6d3697075dde21fd588a94872585407f03ab6d2c0f09bb0b40e2183b6798f3719123b8e9651",
          "sha256": "e0b6bf3a8d8e1918f7d8b09b60545178290bd0f5e15641180b3c2d50dca060bd",
          "sha1": "4a7fce67686e713c5581647cf85219fa28fb6687",
          "md5": "aab12ba16642a5a17bae48b7e6d3b57e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vesper-1.0.11-sources.jar",
          "url": "vesper-1.0.11-sources.jar",
          "size": 101835,
          "sha512": "01982d0820443b02d9a3bad87cd5822ba50c9e8ece9e2e0a80f7dc43fcd9da0ff616641295510702c76ea0c33e69ba475b2ab05ed828a736e0cfa978f3405dca",
          "sha256": "dc529d1d75699718eefe7dd921ebde4fe1192d30f80b56c1cc48df108bf0006a",
          "sha1": "2fb762c88287016fadceffa292f4f489af64f1e7",
          "md5": "5fb2c10a9da023bdaa9cb1a9d5fedcbf"
        }
      ]
    }
  ]
}
