{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.codexbat",
    "module": "vesper",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vesper-1.0.12.jar",
          "url": "vesper-1.0.12.jar",
          "size": 162292,
          "sha512": "bb601ce264d6203bfcdc08da2ac3c937e15608e61a61e8a3201308809d3fedcab7d377fd1f85bde6e5bad81801fb4dcbed7c9b71ed2749f3a8c7681f1cb6c48a",
          "sha256": "26918e70bc433e7d895a02b80dffe6c5a0765310f97521a794240b72cae852be",
          "sha1": "80a4568b9841e01db6c72cc2580889a32e10e31e",
          "md5": "6f9796b509d1a048be96511a540faaba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "vesper-1.0.12.jar",
          "url": "vesper-1.0.12.jar",
          "size": 162292,
          "sha512": "bb601ce264d6203bfcdc08da2ac3c937e15608e61a61e8a3201308809d3fedcab7d377fd1f85bde6e5bad81801fb4dcbed7c9b71ed2749f3a8c7681f1cb6c48a",
          "sha256": "26918e70bc433e7d895a02b80dffe6c5a0765310f97521a794240b72cae852be",
          "sha1": "80a4568b9841e01db6c72cc2580889a32e10e31e",
          "md5": "6f9796b509d1a048be96511a540faaba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vesper-1.0.12-sources.jar",
          "url": "vesper-1.0.12-sources.jar",
          "size": 101835,
          "sha512": "f5e6cd0f1df04aadaddd62c8e4702a0bf72b70d2d71ec4d9ac8ec325449a175143646e337719e498a1f8b34adf4b428158a14e73c05d0c9d98f586f5e4f7a3b3",
          "sha256": "db68ec1d9c264d6e5de0346eff11e24c9b87c4d29fd7ec8d9918fae5162d05be",
          "sha1": "84f543e5ee76b7239ed2b875016608948aed5290",
          "md5": "702b6dad5bdd9da49b79b579fc41ac8f"
        }
      ]
    }
  ]
}
