{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.codexbat",
    "module": "vesper",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vesper-1.0.13.jar",
          "url": "vesper-1.0.13.jar",
          "size": 162293,
          "sha512": "5e17428ada04f09dcddf9a042d1dd79a79a70e93a52a469e51ce5db25902e8d05363446a05a034408b3c6b221acc8f998a529e52c92882d7a214ea75404db6ec",
          "sha256": "a7d0fd3c0381b2b13758ff972bca9164c220643ba139128c0b490ba4b0ebdddb",
          "sha1": "b2e95bde5f033077581ddfece38ee5601f43a02c",
          "md5": "49c22e0906a737b5a807fa6352ef74bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "vesper-1.0.13.jar",
          "url": "vesper-1.0.13.jar",
          "size": 162293,
          "sha512": "5e17428ada04f09dcddf9a042d1dd79a79a70e93a52a469e51ce5db25902e8d05363446a05a034408b3c6b221acc8f998a529e52c92882d7a214ea75404db6ec",
          "sha256": "a7d0fd3c0381b2b13758ff972bca9164c220643ba139128c0b490ba4b0ebdddb",
          "sha1": "b2e95bde5f033077581ddfece38ee5601f43a02c",
          "md5": "49c22e0906a737b5a807fa6352ef74bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vesper-1.0.13-sources.jar",
          "url": "vesper-1.0.13-sources.jar",
          "size": 101835,
          "sha512": "f5e6cd0f1df04aadaddd62c8e4702a0bf72b70d2d71ec4d9ac8ec325449a175143646e337719e498a1f8b34adf4b428158a14e73c05d0c9d98f586f5e4f7a3b3",
          "sha256": "db68ec1d9c264d6e5de0346eff11e24c9b87c4d29fd7ec8d9918fae5162d05be",
          "sha1": "84f543e5ee76b7239ed2b875016608948aed5290",
          "md5": "702b6dad5bdd9da49b79b579fc41ac8f"
        }
      ]
    }
  ]
}
