{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.codexbat",
    "module": "vesper",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vesper-1.0.15.jar",
          "url": "vesper-1.0.15.jar",
          "size": 162293,
          "sha512": "fad0923cb19e815f3d7a507da8407279c30e8b74d32b6f59a9f9a241221069685837dfa47204a18022319967d3ca9363c31ddf08e425f0011a31726600df7715",
          "sha256": "b903ec25b8241f859d1e92529073e16c10c365b04ae207d4717139176e8bf1ac",
          "sha1": "12eaf1f612bdd84ab1cf56cbbb7951023d33537d",
          "md5": "ffccff220082d4f9bb24df4fbb55e232"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "vesper-1.0.15.jar",
          "url": "vesper-1.0.15.jar",
          "size": 162293,
          "sha512": "fad0923cb19e815f3d7a507da8407279c30e8b74d32b6f59a9f9a241221069685837dfa47204a18022319967d3ca9363c31ddf08e425f0011a31726600df7715",
          "sha256": "b903ec25b8241f859d1e92529073e16c10c365b04ae207d4717139176e8bf1ac",
          "sha1": "12eaf1f612bdd84ab1cf56cbbb7951023d33537d",
          "md5": "ffccff220082d4f9bb24df4fbb55e232"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vesper-1.0.15-sources.jar",
          "url": "vesper-1.0.15-sources.jar",
          "size": 101835,
          "sha512": "f5e6cd0f1df04aadaddd62c8e4702a0bf72b70d2d71ec4d9ac8ec325449a175143646e337719e498a1f8b34adf4b428158a14e73c05d0c9d98f586f5e4f7a3b3",
          "sha256": "db68ec1d9c264d6e5de0346eff11e24c9b87c4d29fd7ec8d9918fae5162d05be",
          "sha1": "84f543e5ee76b7239ed2b875016608948aed5290",
          "md5": "702b6dad5bdd9da49b79b579fc41ac8f"
        }
      ]
    }
  ]
}
