{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.codexbat",
    "module": "vesper",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vesper-1.0.10.jar",
          "url": "vesper-1.0.10.jar",
          "size": 162293,
          "sha512": "7a8628a567cf1ddab6b61660053f6d32410eb3408012c4b3f3f8bf8e271fa0437b6e37e22874b31f8623c7a4e5caca5a6ddc09665b91dcdd80ce84ae8e9497bf",
          "sha256": "cc9d7d62128dcebc903914dd688d4f35fd960f941e71ccf45f0483bdfba7c49d",
          "sha1": "e813330e4c3da430e034cc4540e9e46b9d1b87cb",
          "md5": "e39d5afb8db58199f010748f5086967c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "vesper-1.0.10.jar",
          "url": "vesper-1.0.10.jar",
          "size": 162293,
          "sha512": "7a8628a567cf1ddab6b61660053f6d32410eb3408012c4b3f3f8bf8e271fa0437b6e37e22874b31f8623c7a4e5caca5a6ddc09665b91dcdd80ce84ae8e9497bf",
          "sha256": "cc9d7d62128dcebc903914dd688d4f35fd960f941e71ccf45f0483bdfba7c49d",
          "sha1": "e813330e4c3da430e034cc4540e9e46b9d1b87cb",
          "md5": "e39d5afb8db58199f010748f5086967c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vesper-1.0.10-sources.jar",
          "url": "vesper-1.0.10-sources.jar",
          "size": 101835,
          "sha512": "01982d0820443b02d9a3bad87cd5822ba50c9e8ece9e2e0a80f7dc43fcd9da0ff616641295510702c76ea0c33e69ba475b2ab05ed828a736e0cfa978f3405dca",
          "sha256": "dc529d1d75699718eefe7dd921ebde4fe1192d30f80b56c1cc48df108bf0006a",
          "sha1": "2fb762c88287016fadceffa292f4f489af64f1e7",
          "md5": "5fb2c10a9da023bdaa9cb1a9d5fedcbf"
        }
      ]
    }
  ]
}
