{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.codexbat",
    "module": "vesper",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vesper-1.0.14.jar",
          "url": "vesper-1.0.14.jar",
          "size": 162293,
          "sha512": "a45570822850094be7e87c7097a99eac6451a77faa2c5ad984e439ed1d5b66106f6f0be19663eed4fefcec6fe4beccdc7232ab4d1383ce9dc695b9bee4a71f10",
          "sha256": "5497bb0144bc0242907818640467e93e8f03a83297ec69b988cf5975538bf6c3",
          "sha1": "a31ee080946aea93062b6ea7c3444e24595db034",
          "md5": "1df296503b871120a15fb6d6240da05d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "vesper-1.0.14.jar",
          "url": "vesper-1.0.14.jar",
          "size": 162293,
          "sha512": "a45570822850094be7e87c7097a99eac6451a77faa2c5ad984e439ed1d5b66106f6f0be19663eed4fefcec6fe4beccdc7232ab4d1383ce9dc695b9bee4a71f10",
          "sha256": "5497bb0144bc0242907818640467e93e8f03a83297ec69b988cf5975538bf6c3",
          "sha1": "a31ee080946aea93062b6ea7c3444e24595db034",
          "md5": "1df296503b871120a15fb6d6240da05d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vesper-1.0.14-sources.jar",
          "url": "vesper-1.0.14-sources.jar",
          "size": 101835,
          "sha512": "f5e6cd0f1df04aadaddd62c8e4702a0bf72b70d2d71ec4d9ac8ec325449a175143646e337719e498a1f8b34adf4b428158a14e73c05d0c9d98f586f5e4f7a3b3",
          "sha256": "db68ec1d9c264d6e5de0346eff11e24c9b87c4d29fd7ec8d9918fae5162d05be",
          "sha1": "84f543e5ee76b7239ed2b875016608948aed5290",
          "md5": "702b6dad5bdd9da49b79b579fc41ac8f"
        }
      ]
    }
  ]
}
